### PR TITLE
Added driveCurrent to TM1652

### PR DESCRIPTION
**Pull request by ColdFireHunter**
I have added the capability to change the drive current.
The drive current can be adjusted in the begin function, and with the setupDisplay function
Added protection if the value is more than 7, will then go to 0.
Value is adjustable from 2/8 till 8/8, not form 1/8 because there is a notice in the datasheet on page 6.
I have tested the changes with Arduino UNO, ESP8266, ESP32, and STM32
Thanks

### CODE REVIEW

**Comment by maxint-rd** [comment]
Hello @ColdFireHunter,

Thank you for your contribution. When implementing support for TM1652 I chose to only support duty cycle, in concordance with the other TM16xx chips (I briefly mentioned that in the code comments).
Can you please tell me for what purpose you are using drive current?
I'd like to reconsider my choice, test your implementation and incorporate it in the main branche in a compatible way.

At the moment I'm redesigning the generic constructor for all chips and still thinking of the best way to support chip-specific features. In the header file comments you can find some hints of the direction I'm taking.
If you have the time, can you please share your thoughts on this and describe how you are using this library?

**Comment by ColdFireHunter** [comment]
@maxint-rd 
Hey, thanks for the reply.
Yes I saw the comments in the code.
Im using the Drive current to account for different LED Colors, so that I can use the same duty cycle. So dimming is easy. 

For example driving red an blue LEDs with the drive curremt i can match brightness at 16/16 duty cycle, an then decrease with the  duty cycle so i get uniform brightness across the display.

I think that a Common constructor is good, Just set all parameters later. Im using the libary for a Display of 164 Displays

On 3.3V deviceses it works normaly just fine, but when the wires get to long it glitches out. Because of not enough voltage.

Best regards

**Comment by maxint-rd** [comment]
Hi @ColdFireHunter , thank you for your reply and for your use of this library. 164 displays? Seriously. Sounds quite impressive! Do you have a picture of the displays you can share? How you multiplex the 164 serial DIN lines? Do you have some devices in between? (FYI in one of my other project I'm using ATtiny13A chips as I2C-slave bridges to drive multiple TM16xx chips and address them over a single I2C connection).

Based on what you stated, I will incorporate your changes, but expect me to also integrate some changes of my own; perhaps in a later version.

**Comment by ColdFireHunter** [comment]
Hi @maxint-rd 
Yes fir 164 diaplays. I will Upload a picture soon. 
Im using two big STM32 to Drive each DIN directly over a level translator. So each driver gets a proper data signal. And i can Change the content rapidly.

Okay very cool, im always open to improvments.

**Comment by ColdFireHunter** [comment]
Hi, thank you for merging :)
I finished the project early last year.
Im sorry that I did not post a photo.

I can also report to you that the code works very well.

**Comment by maxint-rd** [comment]
Hello @ColdFireHunter - good to read the code is working. I haven't tested a setting the current of a TM1652 yet, other than some tryouts when developing the first version. 

I'm still interested to see your project, so when you have the time, feel free to upload a picture (or multiple).

**Pull request merged**
